#!/usr/bin/env bash

bw-unlock() {
    local bw_status job_number
    bw_status="$(bw status | jq -r '.status')"
    case "${bw_status}" in
        locked)
            export BW_SESSION="$(bw unlock --raw < /dev/tty)"
            ;;
        unauthorized)
            export BW_SESSION="$(bw login --raw < /dev/tty)"
            ;;
        unlocked)
            ;;
    esac
    bw_status="$(bw status | jq -r '.status')"
    echo "Bitwarden: ${bw_status}"
    (bw-lock 1 &)
}

bw-lock() {
    local timeout sleep_time
    timeout=0

    [[ "$#" -gt 0 ]] && timeout="${1}"

    sleep_time=$(( timeout * 60 ))
    sleep ${sleep_time}

    bw lock 
}
