#!/usr/bin/env bash

bw-unlock() {
    local bw_status job_number timeout
    timeout=15
    
    if [[ -n ${1} ]]; then
        timeout=${1}
    elif [[ -f "$HOME/.config/git-credential-bw/config" ]]; then
        while IFS= read -r line; do
            key=$(echo "${line}" | cut -d= -f1)
            value=$(echo "${line}" | cut -d= -f2)

            case ${key} in
                timeout)
                    timeout=${value}
                    ;;
                *)
                    ;;
            esac
        done < "$HOME/.config/git-credential-bw/config"
    fi 
    bw_status="$(bw status 2>/dev/null | jq -R -r 'fromjson? | .status')"
    case "${bw_status}" in
        locked)
            export BW_SESSION="$(bw unlock --raw < /dev/tty)"
            ;;
        unauthorized)
            export BW_SESSION="$(bw login --raw < /dev/tty)"
            ;;
        unlocked)
            ;;
    esac
    bw_status="$(bw status 2>/dev/null | jq -R -r 'fromjson? | .status')"
    echo "Bitwarden: ${bw_status}"
    (bw-lock ${timeout} &)
}

bw-lock() {
    local timeout sleep_time
    timeout=0

    [[ "$#" -gt 0 ]] && timeout="${1}"

    sleep_time=$(( timeout * 60 ))
    sleep ${sleep_time}

    bw lock 
}
