#!/usr/bin/env bash

bw-unlock() {
    local bw_status
    bw_status="$(bw status | jq -r '.status')"
    case "${bw_status}" in
        locked)
            export BW_SESSION="$(bw unlock --raw < /dev/tty)"
            ;;
        unauthorized)
            export BW_SESSION="$(bw login --raw < /dev/tty)"
            ;;
        unlocked)
            ;;
    esac
    bw_status="$(bw status | jq -r '.status')"
    echo "Bitwarden: ${bw_status}"
}
