#!/usr/bin/env bash

log() {
    local level message

    level="${1}"
    message="${2}"

    [[ ! -d "$(dirname ${LOG_FILE})" ]] && mkdir -p "$(dirname ${LOG_FILE})"

    echo -e "[${level}]\t${message}" >> "${LOG_FILE}"
}

get_bw_status() {
    bw_status=$(bw status | jq -r '.status')
    echo "${bw_status}"
}

LOG_FILE=~/tmp/logs/git-credential-bw.log

if ! which bw &>/dev/null; then
    log "ERROR" "Could not find Bitwarden CLI" >&2
    exit 1
fi

while IFS= read -r line; do
    key="$(echo "${line}" | cut -d'=' -f1)"
    value="$(echo "${line}" | cut -d'=' -f2)"

    case "${key}" in
        protocol)
            log "INFO" "${key}=${value}"
            protocol=${value}
            ;;
        host)
            log "INFO" "${key}=${value}"
            host=${value}
            ;;
        username)
            log "INFO" "${key}=${value}"
            username=${value}
            ;;
        password)
            log "INFO" "${key}=********"
            ;;
        *)
            ;;
    esac
done < /dev/stdin

[[ -z "${host}" ]] && { log "ERROR" "Host not provided!"; exit 1; }
[[ -z "${username}" ]] && { log "ERROR" "Username not provided!"; exit 1; }

maxAttempts=3
attempts=0
while [[ ${attempts} -lt ${maxAttempts} ]]; do 
    bw_status=$(get_bw_status)
    case "${bw_status}" in
        unauthenticated)
            log "ERROR" "Bitwarden CLI is unauthenticated!"
            echo "Please login to bitwarden." >&2
            export BW_SESSION="$(bw login --raw < /dev/tty)"
            ;;
        locked)
            log "ERROR" "Bitwarden CLI is locked!"
            echo "Please unlock bitwarden." >&2
            export BW_SESSION="$(bw unlock --raw < /dev/tty)"
            ;;
        unlocked)
            break
            ;;
    esac
    
    [[ "$(get_bw_status)" == "unlocked" ]] && break

    (( attempts++ ))
done

if [[ $(get_bw_status) != "unlocked" ]]; then
    log "ERROR" "Bitwarden not unlocked!"
    echo "Error: Bitward not unlocked!" >&2
    exit 1
fi
    
gitpass=$(bw list items --search ${host} | jq -r '.[] | select(.login.username == "'"${username}"'").fields[] | select(.name == "pat").value')
if [[ -z "${gitpass}" ]]; then
    gitpass=$(bw list items --search ${host} | jq -r '.[] | select(.login.username == "'"${username}"'").login.password')
fi

[[ -z "${gitpass}" ]] && { log "ERROR" "Could not find password in credential store"; exit 1; }
    
echo -e "protocol=${protocol}\nhost=${host}\nusername=${username}\npassword=${gitpass}"
